sonata_admin:
    title: 'Capsule Admin'
    title_logo: '/assets/img/logo-bg.png'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    global_search:
        empty_boxes: fade
        case_sensitive: false

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.stats:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]    